# Generated by Django 6.1 on 2026-09-01 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=256)),
                ('task_priority', models.CharField(max_length=30)),
                ('task_status', models.CharField(max_length=30)),
                ('task_added_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
