# Generated by Django 6.1 on 2026-09-03 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='task_status',
            field=models.BooleanField(default=False),
        ),
    ]
