# Generated by Django 6.1 on 2026-09-03 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0002_alter_taskmodel_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='task_description',
            field=models.TextField(default='Add texts here'),
        ),
    ]
