# Generated by Django 6.1 on 2026-09-03 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0003_taskmodel_task_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='task_description',
            field=models.TextField(default='Add Task Description here'),
        ),
    ]
