# Generated by Django 6.1 on 2026-09-07 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0006_alter_taskmodel_task_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='task_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], default='Pending', max_length=30),
        ),
    ]
